# --- !Ups
create table "LOCATIONS" ("id" SERIAL NOT NULL PRIMARY KEY,"name" VARCHAR(25) NOT NULL);
create table "EVENTTYPES" ("id" SERIAL NOT NULL PRIMARY KEY,"name" VARCHAR(25) NOT NULL);
create table "EVENTS" ("int" SERIAL NOT NULL PRIMARY KEY,"eventTypeId" INTEGER NOT NULL,"date" DATE NOT NULL,"locationId" INTEGER NOT NULL,"name" VARCHAR(50) NOT NULL);
create unique index "idx" on "EVENTS" ("eventTypeId","date","locationId");
create table "AGENDATYPES" ("id" SERIAL NOT NULL PRIMARY KEY,"name" VARCHAR(25) NOT NULL,"parent" INTEGER);
create table "EVENTTYPEAGENDA" ("id" INTEGER NOT NULL,"eventTypeId" INTEGER NOT NULL,"agendaTypeId" INTEGER NOT NULL);
alter table "EVENTTYPEAGENDA" add constraint "pk_agendaItem" primary key("id","eventTypeId","agendaTypeId");
create table "CONTACTS" ("id" SERIAL NOT NULL PRIMARY KEY,"givenName" VARCHAR(50) NOT NULL,"lastName" VARCHAR(50) NOT NULL,"groupId" VARCHAR(50),"notes" VARCHAR);
create table "CONTACTPREFERENCES" ("columnId" INTEGER NOT NULL,"agendaTypeId" INTEGER NOT NULL,"prefer" BOOLEAN NOT NULL);
alter table "CONTACTPREFERENCES" add constraint "pk_contactPreferences" primary key("columnId","agendaTypeId");
create table "EVENTAGENDAITEMS" ("id" INTEGER NOT NULL,"eventId" INTEGER NOT NULL,"agendaTypeId" INTEGER NOT NULL,"prenotes" VARCHAR NOT NULL,"contactId" INTEGER DEFAULT null,"postnotes" VARCHAR NOT NULL);
alter table "EVENTAGENDAITEMS" add constraint "pk_eventAgendaItems" primary key("id","eventId");
alter table "EVENTS" add constraint "event_fk_eventTypeId" foreign key("eventTypeId") references "EVENTTYPES"("id") on update CASCADE on delete RESTRICT;
alter table "EVENTS" add constraint "event_fk_locationId" foreign key("locationId") references "LOCATIONS"("id") on update CASCADE on delete RESTRICT;
alter table "AGENDATYPES" add constraint "fk_agendaTypeParent" foreign key("parent") references "AGENDATYPES"("id") on update CASCADE on delete RESTRICT;
alter table "EVENTTYPEAGENDA" add constraint "fk_agendaTypes" foreign key("agendaTypeId") references "AGENDATYPES"("id") on update CASCADE on delete RESTRICT;
alter table "EVENTTYPEAGENDA" add constraint "fk_eventTypes" foreign key("eventTypeId") references "EVENTTYPES"("id") on update CASCADE on delete RESTRICT;
alter table "CONTACTPREFERENCES" add constraint "fk_cpAgendaTypes" foreign key("agendaTypeId") references "AGENDATYPES"("id") on update CASCADE on delete RESTRICT;
alter table "CONTACTPREFERENCES" add constraint "fk_cpContacts" foreign key("columnId") references "CONTACTS"("id") on update CASCADE on delete RESTRICT;
alter table "EVENTAGENDAITEMS" add constraint "fk_agendaTypes" foreign key("agendaTypeId") references "AGENDATYPES"("id") on update CASCADE on delete RESTRICT;
alter table "EVENTAGENDAITEMS" add constraint "fk_eaiContacts" foreign key("contactId") references "CONTACTS"("id") on update CASCADE on delete RESTRICT;
alter table "EVENTAGENDAITEMS" add constraint "fk_events" foreign key("eventId") references "EVENTS"("int") on update CASCADE on delete RESTRICT;

# --- !Downs
alter table "EVENTAGENDAITEMS" drop constraint "fk_agendaTypes";
alter table "EVENTAGENDAITEMS" drop constraint "fk_eaiContacts";
alter table "EVENTAGENDAITEMS" drop constraint "fk_events";
alter table "CONTACTPREFERENCES" drop constraint "fk_cpAgendaTypes";
alter table "CONTACTPREFERENCES" drop constraint "fk_cpContacts";
alter table "EVENTTYPEAGENDA" drop constraint "fk_agendaTypes";
alter table "EVENTTYPEAGENDA" drop constraint "fk_eventTypes";
alter table "AGENDATYPES" drop constraint "fk_agendaTypeParent";
alter table "EVENTS" drop constraint "event_fk_eventTypeId";
alter table "EVENTS" drop constraint "event_fk_locationId";
alter table "EVENTAGENDAITEMS" drop constraint "pk_eventAgendaItems";
drop table "EVENTAGENDAITEMS";
alter table "CONTACTPREFERENCES" drop constraint "pk_contactPreferences";
drop table "CONTACTPREFERENCES";
drop table "CONTACTS";
alter table "EVENTTYPEAGENDA" drop constraint "pk_agendaItem";
drop table "EVENTTYPEAGENDA";
drop table "AGENDATYPES";
drop table "EVENTS";
drop table "EVENTTYPES";
drop table "LOCATIONS";